# Generated by Django 6.0.5 on 2026-05-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_category_options_alter_file_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='process_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='process_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='file',
            name='process_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
