# Generated by Django 6.0.5 on 2026-05-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_file_process_message_file_process_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='ai_analysis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
