# Generated by Django 6.0.5 on 2026-05-27 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_file_ai_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='source',
            field=models.CharField(choices=[('knowledge_base', '知识库'), ('ai_chat', 'AI助手')], default='knowledge_base', max_length=20),
        ),
    ]
