# Generated by Django 6.0.5 on 2026-05-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_file_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='keywords',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
